spring:
  application:
    name: Crypto Currency Monitor (RxJava)
debug: false
logging:
  level:
    root: info
server:
  port: 8082
custom.property:
  proxy:
    host: proxy.corp.com
    port: 8080
    enabled: false
  coin.service.uri: https://api.coinbase.com/v2/prices/{currPair}/buy
  crypto:
    name: BTC
    curr: USD
  interval.msecs: 2000
  message:
    stomp.endpoint: /price-websocket
    topic: /topic/price
